# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Anennya's musings
email: anennya@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A site to share what I am learning!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://anennya.com" # the base hostname & protocol for your site
twitter_username: anennya
github_username:  anennya

# Build settings
markdown: kramdown
